#!/usr/bin/env sh
# gen-learnings-index.sh -- regenerate the by-tag index in docs/LEARNINGS.md.
# Reads each `## L-NNN [tags: ...]` heading and rewrites the block between the
# <!-- INDEX:START --> / <!-- INDEX:END --> markers. Idempotent; touches only
# between the markers, never the entries. See ADR-009 (metadata SSOT + derived index).
#
# Usage:
#   sh scripts/gen-learnings-index.sh            regenerate the index in place
#   sh scripts/gen-learnings-index.sh --check    exit 1 if the index is stale (CI / qa-check), no write

set -u
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
FILE="$ROOT/docs/LEARNINGS.md"
TAGS="process docs tooling edit-safety sprint-model"

[ -f "$FILE" ] || { echo "gen-index: missing $FILE" >&2; exit 2; }
grep -q '<!-- INDEX:START' "$FILE" && grep -q '<!-- INDEX:END' "$FILE" || {
  echo "gen-index: INDEX markers not found in $FILE" >&2; exit 2; }

tmp=$(mktemp)
# 1. everything through the START marker (kept verbatim)
sed -n '1,/<!-- INDEX:START/p' "$FILE" >> "$tmp"
# 2. the generated body
printf '\n**Index** — learnings by tag (generated by `scripts/gen-learnings-index.sh`):\n\n' >> "$tmp"
for tag in $TAGS; do
  ids=$(grep -E '^## L-[0-9]+ \[tags:' "$FILE" \
        | grep -E "\[tags:[^]]*$tag" \
        | sed -E 's/^## (L-[0-9]+) .*/\1/' \
        | paste -sd '@' -)
  [ -n "$ids" ] || continue
  ids=$(printf '%s' "$ids" | sed 's/@/ · /g')
  printf -- '- **%s** — %s\n' "$tag" "$ids" >> "$tmp"
done
printf '\n' >> "$tmp"
# 3. from the END marker to EOF (kept verbatim)
sed -n '/<!-- INDEX:END/,$p' "$FILE" >> "$tmp"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$tmp" "$FILE"; then echo "PASS  gen-index: LEARNINGS index current"; rm -f "$tmp"; exit 0
  else echo "FAIL  gen-index: LEARNINGS index STALE — run: sh scripts/gen-learnings-index.sh" >&2; rm -f "$tmp"; exit 1; fi
fi
mv "$tmp" "$FILE"
echo "gen-index: regenerated the LEARNINGS tag index"
