#!/usr/bin/env sh
# gen-index.sh -- regenerate the by-tag / by-domain knowledge index in docs/knowledge-index.md
# from write-time frontmatter (ADR-009 SSOT): LEARNINGS `## L-NNN [tags:]` headings + per-file
# frontmatter on docs/adr/*.md and docs/research/*.md. Idempotent; rewrites only between the
# <!-- INDEX:START --> / <!-- INDEX:END --> markers. The vocab (TAGS/DOMAINS) is the single origin
# that qa-check.sh sources for its completeness lint. See ADR-009.
#
# Usage:
#   sh scripts/gen-index.sh            regenerate docs/knowledge-index.md in place
#   sh scripts/gen-index.sh --check    exit 1 if the index is stale (CI / qa-check), no write

set -u
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
OUT="$ROOT/docs/knowledge-index.md"
LEARN="$ROOT/docs/LEARNINGS.md"
TAGS="process docs tooling edit-safety sprint-model"
DOMAINS="skills doc-standard governance knowledge sprint-model"

[ -f "$OUT" ] || { echo "gen-index: missing $OUT" >&2; exit 2; }
grep -q '<!-- INDEX:START' "$OUT" && grep -q '<!-- INDEX:END' "$OUT" || {
  echo "gen-index: INDEX markers not found in $OUT" >&2; exit 2; }

# extract a frontmatter field value (first match inside the leading --- block)
fm() { # <file> <field>
  awk -v f="$2" '
    NR==1 && $0!="---"{exit} NR==1{next}
    $0=="---"{exit}
    $0 ~ "^"f":"{sub("^"f":[ ]*","");print;exit}' "$1"
}
listwords() { printf '%s' "$1" | tr -d '[],'; }  # "[a, b]" -> "a b"

entries=$(mktemp)  # rows: <src>\t<id>\t<link>\t<space-tags>\t<domain>

grep -E '^## L-[0-9]+ \[tags:' "$LEARN" 2>/dev/null | while IFS= read -r line; do
  id=$(printf '%s' "$line" | sed -E 's/^## (L-[0-9]+) .*/\1/')
  tg=$(printf '%s' "$line" | sed -E 's/.*\[tags: ([^]]*)\].*/\1/')
  printf '%s\t%s\t%s\t%s\t%s\n' learn "$id" "LEARNINGS.md" "$tg" "-" >> "$entries"
done

for f in "$ROOT"/docs/adr/ADR-*.md "$ROOT"/docs/research/*.md; do
  [ -f "$f" ] || continue
  id=$(fm "$f" id); [ -n "$id" ] || continue
  tg=$(listwords "$(fm "$f" tags)")
  dm=$(fm "$f" domain); [ -n "$dm" ] || dm="-"
  link=$(printf '%s' "$f" | sed -E "s#^$ROOT/docs/##")
  case "$f" in */adr/*) src=adr ;; *) src=research ;; esac
  printf '%s\t%s\t%s\t%s\t%s\n' "$src" "$id" "$link" "$tg" "$dm" >> "$entries"
done

gen() {
  printf '\n**Knowledge index** — generated by `scripts/gen-index.sh` from write-time frontmatter (ADR-009).\n'
  printf '\n### By tag\n\n'
  for tag in $TAGS; do
    ids=$(awk -F '\t' -v t="$tag" '{n=split($4,a," ");for(i=1;i<=n;i++)if(a[i]==t)printf "[%s](%s) · ",$2,$3}' "$entries")
    ids=${ids% · }
    [ -n "$ids" ] && printf -- '- **%s** — %s\n' "$tag" "$ids"
  done
  printf '\n### By domain (ADR + research)\n\n'
  for dm in $DOMAINS; do
    ids=$(awk -F '\t' -v d="$dm" '$5==d{printf "[%s](%s) · ",$2,$3}' "$entries")
    ids=${ids% · }
    [ -n "$ids" ] && printf -- '- **%s** — %s\n' "$dm" "$ids"
  done
  printf '\n'
}

tmp=$(mktemp)
today=$(date +%F)
sed -n '1,/<!-- INDEX:START/p' "$OUT" \
  | awk -v d="$today" '{ if ($0 ~ /^last_updated:/) print "last_updated: " d; else print }' >> "$tmp"
gen >> "$tmp"
sed -n '/<!-- INDEX:END/,$p' "$OUT" >> "$tmp"
rm -f "$entries"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$tmp" "$OUT"; then echo "PASS  gen-index: knowledge index current"; rm -f "$tmp"; exit 0
  else echo "FAIL  gen-index: knowledge index STALE — run: sh scripts/gen-index.sh" >&2; rm -f "$tmp"; exit 1; fi
fi
mv "$tmp" "$OUT"
echo "gen-index: regenerated docs/knowledge-index.md"
