#!/usr/bin/env sh
# gen-index.sh -- regenerate the by-tag / by-domain knowledge index in docs/knowledge-index.md
# from write-time frontmatter (ADR-009 SSOT): LEARNINGS `## L-NNN [tags:]` headings + per-file
# frontmatter on docs/adr/*.md and docs/research/*.md. Idempotent over the WHOLE file: a run that
# finds no content change leaves the file byte-identical, `last_updated` included (SPRINT-093 T2 /
# TD-111 -- last_updated used to be wall-clock-stamped every run, which alone went stale at
# midnight). Only a genuine content change advances `last_updated` and rewrites between the
# <!-- INDEX:START --> / <!-- INDEX:END --> markers. The vocab (TAGS/DOMAINS) is the single origin
# that qa-check.sh sources for its completeness lint. See ADR-009.
#
# Usage:
#   sh scripts/gen-index.sh            regenerate docs/knowledge-index.md in place
#   sh scripts/gen-index.sh --check    exit 1 if the index is stale (CI / qa-check), no write

set -u
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
OUT="$ROOT/docs/knowledge-index.md"
LEARN="$ROOT/docs/LEARNINGS.md"
TAGS="process docs tooling edit-safety sprint-model"
DOMAINS="skills doc-standard governance knowledge sprint-model"

[ -f "$OUT" ] || { echo "gen-index: missing $OUT" >&2; exit 2; }
grep -q '<!-- INDEX:START' "$OUT" && grep -q '<!-- INDEX:END' "$OUT" || {
  echo "gen-index: INDEX markers not found in $OUT" >&2; exit 2; }

listwords() { printf '%s' "$1" | tr -d '[],'; }  # "[a, b]" -> "a b"

# _split_row <row> -- sets $_row_id/$_row_tg/$_row_dm from a "id|tags|domain" row. A FUNCTION,
# deliberately: `set --` inside one only replaces THIS function's own positional parameters (POSIX
# scoping), restored on return -- called at top level instead, it would silently overwrite the
# SCRIPT's own $1 (this script's own "--check" argument), which is read again after this loop, near
# the bottom of the file. That exact mistake was caught only by re-running --check after the rewrite
# and seeing it silently take the write path instead of reporting stale/current.
_split_row() {
  _sr_ifs=$IFS; IFS='|'
  set -- $1
  IFS=$_sr_ifs
  _row_id=${1:-}; _row_tg=${2:-}; _row_dm=${3:-}
}

entries=$(mktemp)  # rows: <src>\t<id>\t<link>\t<space-tags>\t<domain>

# SPAWN-FREE (L-144 shape, same as scripts/lib/conformance-engine.sh's ownership family and its
# driver): the previous version ran a `grep` producing N heading lines, then TWO `sed` processes per
# line -- for the 143 LEARNINGS entries on this repo, 286 external processes on this host alone.
# Everything a heading line needs (id, tags) is extractable with the string ops awk already has, in
# one pass over the file. Measured: 15s (this loop's own share) -> well under a second.
awk '
  /^## L-[0-9]+ \[tags:/ {
    id = $0; sub(/^## /, "", id); sub(/ .*/, "", id)
    tg = $0; sub(/.*\[tags: /, "", tg); sub(/\].*/, "", tg)
    printf "learn\t%s\tLEARNINGS.md\t%s\t-\n", id, tg
  }
' "$LEARN" >> "$entries"

# docs/research/archive/ is included deliberately (SPRINT-055 T3): a superseded verdict is usually
# the WHY-trail for whatever replaced it, so dropping it from the index at archive time would make
# the trail findable only by knowing the path. Archived entries are marked so the index does not
# present a spent verdict as current.
#
# SPAWN-FREE per file: the previous version called `fm` (its own awk process) three times per file --
# id, tags, domain -- 3 x ~79 corpus files = 237 processes. One combined awk pass per file extracts
# all three from the one frontmatter block it already has to read. Still one process PER FILE
# (not one process for the whole corpus): a single cross-file awk needs a state machine and can
# silently drop a zero-byte file at FNR==1, which is the failure this repo's ownership family
# deliberately avoided the same way (scripts/lib/conformance-engine.sh, `_own_docs`/`_own_scan`
# comment). "|" is the row delimiter here (not tab) because it is what the rest of this codebase's
# reduced-row emitters use (`_s2_rows` in conformance-engine.sh) and cannot collide with an id, tag
# word or domain value in this vocabulary.
for f in "$ROOT"/docs/adr/ADR-*.md "$ROOT"/docs/research/*.md "$ROOT"/docs/research/archive/*.md; do
  [ -f "$f" ] || continue
  row=$(awk '
    NR==1 && $0!="---"{exit}
    NR==1{next}
    $0=="---"{exit}
    $0~"^id:"{v=$0; sub("^id:[ ]*","",v); id=v}
    $0~"^tags:"{v=$0; sub("^tags:[ ]*","",v); tg=v}
    $0~"^domain:"{v=$0; sub("^domain:[ ]*","",v); dm=v}
    END{printf "%s|%s|%s", id, tg, dm}
  ' "$f")
  _split_row "$row"
  id=$_row_id; tg_raw=$_row_tg; dm=$_row_dm
  [ -n "$id" ] || continue
  case "$f" in */research/archive/*) id="$id (archived)" ;; esac
  tg=$(listwords "$tg_raw")
  [ -n "$dm" ] || dm="-"
  link=$(printf '%s' "$f" | sed -E "s#^$ROOT/docs/##")
  case "$f" in */adr/*) src=adr ;; *) src=research ;; esac
  printf '%s\t%s\t%s\t%s\t%s\n' "$src" "$id" "$link" "$tg" "$dm" >> "$entries"
done

gen() {
  printf '\n**Knowledge index** — generated by `scripts/gen-index.sh` from write-time frontmatter (ADR-009).\n'
  printf '\n### By tag\n\n'
  for tag in $TAGS; do
    ids=$(awk -F '\t' -v t="$tag" '{n=split($4,a," ");for(i=1;i<=n;i++)if(a[i]==t)printf "[%s](%s) · ",$2,$3}' "$entries")
    ids=${ids% · }
    [ -n "$ids" ] && printf -- '- **%s** — %s\n' "$tag" "$ids"
  done
  printf '\n### By domain (ADR + research)\n\n'
  for dm in $DOMAINS; do
    ids=$(awk -F '\t' -v d="$dm" '$5==d{printf "[%s](%s) · ",$2,$3}' "$entries")
    ids=${ids% · }
    [ -n "$ids" ] && printf -- '- **%s** — %s\n' "$dm" "$ids"
  done
  printf '\n'
}

# TD-021: tmp must live in the SAME directory as $OUT so the final `mv` below is a
# same-filesystem rename, not a cross-device copy+delete. A bare `mktemp` lands in
# $TMPDIR, which is not guaranteed to share a filesystem with the repo (confirmed on
# this box: with TMPDIR unset, mktemp resolves under /tmp, a different device than the
# repo's D: checkout) — a failure partway through a cross-device copy can publish a
# truncated-but-syntactically-valid file, which is exactly how SPRINT-041's disk-full
# truncated the index from 34 lines to 12. Same-directory mktemp forces a real rename
# instead, so a failed/interrupted generation cannot publish a partial result.
# (The `entries` scratch file above stays on system tmp — it's never moved into place,
# only read and then deleted, so it isn't exposed to this failure mode.)
idxdir=$(dirname "$OUT")
tmp=$(mktemp "$idxdir/.knowledge-index.XXXXXX")
hdr=$(mktemp "$idxdir/.knowledge-index-hdr.XXXXXX")
hdr_dated=$(mktemp "$idxdir/.knowledge-index-hdrd.XXXXXX")
bdy=$(mktemp "$idxdir/.knowledge-index-bdy.XXXXXX")
tail_f=$(mktemp "$idxdir/.knowledge-index-tail.XXXXXX")
trap 'rm -f "$tmp" "$hdr" "$hdr_dated" "$bdy" "$tail_f"' EXIT  # best-effort cleanup if we exit/die early

# TD-111 / SPRINT-093 T2: last_updated used to be re-stamped to today() on every run, so on an
# UNCHANGED tree, crossing midnight alone made this run's output differ from the file already on
# disk -- and --check (a plain `cmp`) reported STALE. Combined with TD-110 (night-run.sh dies on
# any non-zero gate exit, no bypass) that is a refused overnight launch on a correct tree.
# Reproduced live: after rollover the sole diff was `last_updated: <D>` -> `<D+1>`.
# Fix: build the candidate FIRST with the OLD last_updated line copied byte-for-byte from $OUT
# (the header above INDEX:START and the tail below INDEX:END are already verbatim copies of
# $OUT -- only gen()'s body, written between the markers, can differ) and diff THAT candidate
# against $OUT. Only when a genuine content change surfaces does last_updated get re-stamped --
# the passage of time alone never triggers it.
sed -n '1,/<!-- INDEX:START/p' "$OUT" > "$hdr"
sed -n '/<!-- INDEX:END/,$p' "$OUT" > "$tail_f"
gen > "$bdy"
rm -f "$entries"

cat "$hdr" "$bdy" "$tail_f" > "$tmp"

if cmp -s "$tmp" "$OUT"; then
  # Body matches $OUT under the file's EXISTING last_updated -- nothing changed. Leaving the
  # date untouched here (rather than re-stamping unconditionally) is the fix itself: it is what
  # makes an unchanged tree produce a byte-identical file across a midnight boundary.
  if [ "${1:-}" = "--check" ]; then
    echo "PASS  gen-index: knowledge index current"
    rm -f "$tmp" "$hdr" "$hdr_dated" "$bdy" "$tail_f"; exit 0
  fi
  rm -f "$tmp" "$hdr" "$hdr_dated" "$bdy" "$tail_f"
  echo "gen-index: docs/knowledge-index.md already current (no content change)"
  exit 0
fi

# Real content changed (a new/edited L-NNN heading, or an ADR/research frontmatter tag/domain) --
# THIS is what earns a new last_updated stamp, not the calendar.
today=$(date +%F)
awk -v d="$today" '{ if ($0 ~ /^last_updated:/) print "last_updated: " d; else print }' "$hdr" > "$hdr_dated"
cat "$hdr_dated" "$bdy" "$tail_f" > "$tmp"

if [ "${1:-}" = "--check" ]; then
  echo "FAIL  gen-index: knowledge index STALE — run: sh scripts/gen-index.sh" >&2
  rm -f "$tmp" "$hdr" "$hdr_dated" "$bdy" "$tail_f"; exit 1
fi
# NOTE on atomicity: same-directory `mv` is a real rename(2) on POSIX filesystems, which
# is atomic there. This repo runs on Windows/NTFS via Git Bash — `mv` onto an existing
# destination is NOT guaranteed atomic the way POSIX rename(2) is (e.g. an open handle
# on $OUT held by another process can make the replace fail outright rather than commit
# instantaneously). That limit is real and unresolved here, not claimed away; what the
# same-directory tmp *does* guarantee on this platform is that the move is same-volume
# (no cross-device copy+delete), which is what prevented the TD-021 truncation.
mv "$tmp" "$OUT"
rm -f "$hdr" "$hdr_dated" "$bdy" "$tail_f"
echo "gen-index: regenerated docs/knowledge-index.md"
